apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: vlan10-subinterface-leaf1
  namespace: sdc
  labels:
    config.sdcio.dev/targetName: nokia-leaf-1
    config.sdcio.dev/targetNamespace: sdc
spec:
  priority: 20
  config:
  - path: /
    value:
      interface:
      - name: ethernet-1/1
        admin-state: enable
        vlan-tagging: true
        subinterface:
        - index: 10
          admin-state: enable
          type: routed
          vlan:
            encap:
              single-tagged:
                vlan-id: 10
