apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: vlan10-subinterface-leaf2
  namespace: sdc
  labels:
    config.sdcio.dev/targetName: nokia-leaf-2
    config.sdcio.dev/targetNamespace: sdc
spec:
  priority: 20
  config:
  - path: /
    value:
      interface:
      - name: ethernet-1/49
        admin-state: enable
        vlan-tagging: true
        subinterface:
        - index: 10
          admin-state: enable
          type: routed
          ipv4:
            admin-state: enable
            address:
            - ip-prefix: 192.168.10.12/24
          vlan:
            encap:
              single-tagged:
                vlan-id: 10
      network-instance:
      - name: default
        interface:
        - name: ethernet-1/49.10
