apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdc-network-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/reinaldosaraiva/netops-gitops.git
    targetRevision: main
    path: clusters/kind-arista-lab
    directory:
      recurse: true
      include: '{configs/**/*,debug/**/*}'
  destination:
    server: https://kubernetes.default.svc
    namespace: sdc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
