apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: arista-leaf2-interface-desc
  namespace: sdc
  labels:
    config.sdcio.dev/targetName: leaf-2-arista
    config.sdcio.dev/targetNamespace: sdc
spec:
  priority: 10
  config:
  - path: /
    value:
      interfaces:
        interface:
        - name: Ethernet1
          config:
            description: "SDC Managed - Uplink to SPINE-1"
